repos:
  - repo: https://github.com/psf/black
    rev: 24.9.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff
    rev: 0.0.302
    hooks:
      - id: ruff
  - repo: https://github.com/python/mypy
    rev: v1.10
    hooks:
      - id: mypy
